format = """
$directory\
$git_branch
$character"""

[character]
success_symbol = "[](white)"
error_symbol = "[](red)"
vicmd_symbol = "[](green)"

[directory]
style = "blue bold"
format = '[$path]($style) '
truncate_to_repo = false

[git_branch]
symbol = ' '
style = "green bold"
